// react-version/src/components/Dropdown.jsx
import React, {useEffect, useState} from 'react'


const DropDown = ({cities, chosenCity, setChosenCity}) => {
  const [display, setDisplay] = useState('none')

  const handleClick = () => {
    if (display == 'none') {
      setDisplay('block')
    } else {
      setDisplay('none')
    }
  }
  const handleChange = (city) => {
    setChosenCity(city)
    handleClick()
  }

  return (
    <div className="dropdown-wrapper">
      <button className="dropdown-button" onClick={handleClick}>
        <div className="buttonText">{chosenCity}</div>{' '}
        <div className="arrow">^</div>
      </button>
      <div style={{display: display}}>
        {cities.map((e, i) => (
          <button
            className="dropdown-list"
            key={i}
            onClick={() => {
              handleChange(e.toString())
            }}
          >
            {e}
          </button>
        ))}
      </div>
    </div>
  )
}

export default DropDown

// vue-version/src/components/Drop-Down.vue
<template>
  <div className="dropdown-wrapper">
    <button className="dropdown-button" @click="toggleList">
      <div className="buttonText">{{ chosenCity }}</div>
      <div className="arrow">^</div>
    </button>
    <div :style="{ display: display}">
      <button
        className="dropdown-list"
        v-for="(city, index) in props.cities"
        v-bind:key="index"
        @click="$emit('set-city', city)"
      >
        {{ city }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
const props = defineProps({ cities: [String], chosenCity: String })

const display = ref('none')

const toggleList = () => {
  display.value = display.value === 'none' ? 'block' : 'none'
   console.log('clicked')
}

</script>
<script>
export default {
  name: 'DropDown'
}
</script>
<style></style>
