// vue-version/src/components/CityList.vue
<template>
  <div className="card-wrapper">
    <div className="dropdown-card-wrapper" v-if="dropDownCityList.length !== 0">
      <Dropdown
        :cities="dropDownCityList"
        :chosenCity="chosenCity"
      />

      <div className="city-wrapper" v-if="cities != undefined && cities.length !== 0">
        <City v-for="(city, index) in cities" v-bind:key="{ index }" :city="city" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, watch, ref, onMounted } from 'vue'
import { useStore } from 'vuex'
import Dropdown from './Drop-Down.vue'
import City from './City-View.vue'
import { cities as cityList } from '../utils/cities'

const store = useStore()


const chosenCity = computed(() => store.state.selectedCity)
const dropDownCityList = ref([])


onMounted(() => {
  initializeDropdownCityList()
})

const updateDropdownCityList = (cityToDelete, cityToAdd) => {
  const copy = dropDownCityList.value.filter(it => it != cityToDelete)
  copy.push(cityToAdd)
  dropDownCityList.value = copy
}

const initializeDropdownCityList = () => {
  dropDownCityList.value = cityList.filter((it) => it.city != chosenCity.value).map((it) => it.city)
}

const cities = computed(() => {
  if (chosenCity.value === 'All cities') return store.state.cities
  return store.state.cities.filter((it) => it.name == chosenCity.value)
})

watch(chosenCity, (newValue, oldValue) => {
  updateDropdownCityList(newValue, oldValue)
})


</script>

<style></style>

// react-version/src/components/CityList.jsx
/* eslint-disable indent */
import React, { useState } from 'react'
import City from './City'
import DropDown from './Dropdown'
import { useDispatch, useSelector } from 'react-redux'
import { cities as cityList } from '../utils/cities'


export default function CityList()  {
  const cities = useSelector((state) => state.cities)
  const selectedCity = useSelector((state) => state.selectedCity)
 
  return (
    <div className="card-wrapper">
      <div className="dropdown-card-wrapper">
        <DropDown
          cities={cityList
            .filter((it) => it.city != selectedCity)
            .map((e) => e.city)}
          chosenCity={selectedCity}
        />
        {selectedCity == 'All cities'
          ? cities.map((e, i) => <City key={i} city={e} />)
          : cities
              .filter((e) => e.name == selectedCity)
              .map((e, i) => <City key={i} city={e} />)}
      </div>
    </div>
  )
}
